FROM crpi-d0x3buemxmymp6j4.cn-guangzhou.personal.cr.aliyuncs.com/vincenzo_jiang/redis:latest
RUN mkdir -p /usr/local/etc/redis/
WORKDIR /usr/local/etc/redis/
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]